export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const GET_MOVIE = 'GET_MOVIE';
export const SET_LOADING = 'SET_LOADING';
export const SET_NOMINATION_LIMIT = 'SET_NOMINATION_LIMIT';
export const GET_NOMINATIONS = 'GET_NOMINATIONS';
export const ADD_NOMINATION = 'ADD_NOMINATION';
export const REMOVE_NOMINATION = 'REMOVE_NOMINATION';
export const NOMINATION_ERROR = 'NOMINATION_ERROR';
